### ISSUE TITLE
Readme incorrect p2p port

### ISSUE THREAD

**Issue by 0xdcota** [dappnode/DAppNodePackage-goerli-besu#23]
The readme file indicates the peer traffic is port 30414: 
https://github.com/dappnode/DAppNodePackage-goerli-besu/blob/7c12738fb90a5d6501a70a2ba77e06beab8807f9/README.md?plain=1#L19

However the docker-compose.yml indicates peer traffic is port: 30814
https://github.com/dappnode/DAppNodePackage-goerli-besu/blob/7c12738fb90a5d6501a70a2ba77e06beab8807f9/docker-compose.yml#L20

**Comment by alexpeterson91** [comment]
Thank you good catch, it was missed when this package was adapted from the mainnet package.
